import { StyleSheet } from 'react-native';
import { palette } from './theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: palette.background },
  scroll: { padding: 16, paddingBottom: 40 },
  title: { fontSize: 26, fontWeight: '800', color: palette.text, marginBottom: 12 },
  section: { fontSize: 16, fontWeight: '800', color: palette.text, marginBottom: 8 },
  card: { backgroundColor: 'rgba(30, 41, 59, 0.7)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', borderRadius: 16, padding: 14, marginBottom: 12, shadowColor: '#000', shadowOpacity: 0.25, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  input: { borderWidth: 1, borderColor: palette.border, borderRadius: 12, padding: 14, marginBottom: 10, backgroundColor: palette.inputBg, color: palette.text, fontSize: 16 },
  inputSoft: { borderColor: palette.border, backgroundColor: palette.inputBg },
  button: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: palette.primary, padding: 12, borderRadius: 12 },
  buttonText: { color: '#fff', fontWeight: '700' },
  secondaryButton: { backgroundColor: 'transparent', borderWidth: 1, borderColor: palette.border },
  secondaryText: { color: palette.primary, fontWeight: '700' },
  pill: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: palette.surface, color: palette.text, fontWeight: '700', alignSelf: 'flex-start' },
  muted: { color: palette.muted },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  itemTitle: { fontSize: 16, fontWeight: '700', color: palette.text },
  link: { color: palette.subtext, marginTop: 6, fontWeight: '700' },
  loaderContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 20, backgroundColor: palette.background },
  adminBadge: { color: palette.secondary, fontWeight: '700', marginTop: 4 },
  bannerImage: { width: '100%', height: 160, borderRadius: 10, marginVertical: 8 },
  proofImage: { width: '100%', height: 180, borderRadius: 10, marginVertical: 8 },
  avatar: { width: 96, height: 96, borderRadius: 48, backgroundColor: palette.surface, marginBottom: 8 },
  receiptCard: { borderWidth: 1, borderColor: palette.border, borderRadius: 10, padding: 10, marginBottom: 8 },
  overlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(10,12,24,0.55)' },
  heroTitle: { fontSize: 34, fontWeight: '900', color: palette.text, textAlign: 'center' },
  heroTagline: { fontSize: 16, color: palette.subtext, textAlign: 'center', marginTop: 6, marginBottom: 16, lineHeight: 22 },
  glassCard: { backgroundColor: 'rgba(255,255,255,0.06)', borderColor: 'rgba(255,255,255,0.12)', shadowColor: '#000', shadowOpacity: 0.25, shadowRadius: 16, shadowOffset: { width: 0, height: 10 }, elevation: 8 },
  primaryButton: { backgroundColor: palette.primary, borderRadius: 12, paddingVertical: 14, alignItems: 'center', justifyContent: 'center', shadowColor: palette.primary, shadowOpacity: 0.35, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 8 },
  primaryButtonText: { color: '#fff', fontSize: 16, fontWeight: '800', letterSpacing: 0.3 },
  rememberRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 6 },
  rememberText: { color: palette.subtext, fontSize: 13 },
  linksRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12, gap: 12 },
  linkItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  errorText: { color: palette.error, marginTop: 4, fontWeight: '600' },
  successText: { color: palette.success, marginTop: 4, fontWeight: '600' },
  bannerCard: { width: 240, marginRight: 12 },
  bannerBg: { height: 140, borderRadius: 16, overflow: 'hidden' },
  bannerOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(12,16,32,0.55)' },
  priceBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(15,23,42,0.6)', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12 },
  actionChip: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: palette.surface, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 12, borderWidth: 1, borderColor: palette.border },
  medal: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(251,191,36,0.15)', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12 },
  avatarRing: { padding: 4, borderRadius: 56, borderWidth: 2, borderColor: palette.primary },
  badge: { backgroundColor: palette.surface, borderColor: palette.border, borderWidth: 1, borderRadius: 12, padding: 10, alignItems: 'center', width: 100 },
  balanceCard: { backgroundColor: palette.surface, borderRadius: 18, padding: 16, borderWidth: 1, borderColor: palette.border, marginBottom: 12 },
  balanceValue: { fontSize: 34, fontWeight: '900', color: palette.secondary, marginTop: 4 },
  circleAccent: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(124,58,237,0.25)', alignItems: 'center', justifyContent: 'center' },
  ctaRow: { flexDirection: 'row', gap: 10, marginTop: 12, alignItems: 'stretch' },
  ctaButtonPrimary: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: 14, paddingVertical: 12, borderRadius: 12, backgroundColor: palette.secondary },
  ctaButtonPrimaryText: { color: '#0b1224', fontWeight: '800' },
  ctaButtonGhost: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 12, borderRadius: 12, borderWidth: 1, borderColor: palette.border },
  ctaButtonGhostText: { color: palette.text, fontWeight: '700', textAlign: 'center' },
  statTile: { flex: 1, padding: 10, borderRadius: 12, backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.border },
  chartRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 10, marginVertical: 10 },
  chartBar: { width: 26, borderRadius: 10, backgroundColor: palette.accent },
  movementRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: palette.border },
  movementBadge: { width: 34, height: 34, borderRadius: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  statusPill: { marginTop: 4, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999, textTransform: 'uppercase', fontSize: 12, fontWeight: '800', color: palette.text, alignSelf: 'flex-end' },
  statusApproved: { backgroundColor: 'rgba(16,185,129,0.18)', borderColor: 'rgba(16,185,129,0.35)', borderWidth: 1 },
  statusPending: { backgroundColor: 'rgba(251,191,36,0.18)', borderColor: 'rgba(251,191,36,0.35)', borderWidth: 1 },
  statusRejected: { backgroundColor: 'rgba(248,113,113,0.18)', borderColor: 'rgba(248,113,113,0.35)', borderWidth: 1 },
  heroCardHome: { backgroundColor: 'rgba(15, 23, 42, 0.6)', borderWidth: 1, borderColor: 'rgba(168, 85, 247, 0.3)', borderRadius: 18, padding: 18, marginBottom: 14 },
  heroPillRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  heroPill: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: 'rgba(124,58,237,0.18)' },
  heroPillAlt: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, borderWidth: 1, borderColor: palette.border },
  heroPillText: { color: palette.text, fontWeight: '700' },
  heroHeading: { fontSize: 22, fontWeight: '900', color: palette.text, marginBottom: 6 },
  heroSub: { color: palette.subtext, marginBottom: 10 },
  heroStatsRow: { flexDirection: 'row', gap: 10 },
  statCard: { flex: 1, padding: 12, borderRadius: 14, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface },
  statLabel: { color: palette.muted, fontSize: 12 },
  statValue: { color: '#fbbf24', fontSize: 20, fontWeight: '900' },
  sectionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 4 },
  sectionHint: { color: palette.muted, fontSize: 12 },
  raffleCard: { borderWidth: 1, borderColor: 'rgba(124,58,237,0.2)', backgroundColor: 'rgba(255,255,255,0.04)' },
  raffleTopRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 8, marginBottom: 6 },
  pillRow: { flexDirection: 'row', gap: 6, marginBottom: 6 },
  softPill: { backgroundColor: 'rgba(124,58,237,0.12)' },
  ghostPill: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.08)', color: '#c7d2fe', fontWeight: '700' },
  priceBadgePrimary: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(15,23,42,0.85)', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)' },
  priceBadgeText: { color: '#fff', fontWeight: '800' },
  myRaffleCard: { borderWidth: 1, borderColor: 'rgba(34,211,238,0.25)', backgroundColor: 'rgba(12,18,36,0.9)' },
  statusChip: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: 'rgba(34,211,238,0.12)', borderWidth: 1, borderColor: 'rgba(34,211,238,0.4)' },
  statusWinner: { backgroundColor: 'rgba(251,191,36,0.16)', borderColor: 'rgba(251,191,36,0.45)' },
  statusChipText: { color: '#e2e8f0', fontWeight: '700' },
  ticketRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginVertical: 8 },
  ticketBadge: { width: 40, height: 40, borderRadius: 12, backgroundColor: 'rgba(124,58,237,0.2)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(124,58,237,0.35)' },
  miniBadge: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 12, backgroundColor: 'rgba(251,191,36,0.12)', borderWidth: 1, borderColor: 'rgba(251,191,36,0.3)' },
  ticketGlow: { paddingHorizontal: 14, paddingVertical: 12, borderRadius: 14, backgroundColor: '#fbbf24', shadowColor: '#fbbf24', shadowOpacity: 0.45, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 6 },
  profileHeader: { alignItems: 'center', backgroundColor: 'rgba(12,18,36,0.9)', borderColor: 'rgba(255,255,255,0.1)' },
  avatarGlow: { padding: 6, borderRadius: 64, backgroundColor: 'rgba(124,58,237,0.14)', marginBottom: 8 },
  editButton: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#fbbf24', paddingHorizontal: 14, paddingVertical: 10, borderRadius: 12, marginTop: 10 },
  editButtonText: { color: '#0b1224', fontWeight: '800' },
  superCard: { backgroundColor: 'rgba(12,18,36,0.92)', borderColor: 'rgba(255,255,255,0.08)' },
  sectionIconCircle: { width: 28, height: 28, borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.08)', alignItems: 'center', justifyContent: 'center', marginRight: 8 },
  bannerPreview: { marginVertical: 8 },
  bannerPreviewImage: { height: 140, borderRadius: 12, overflow: 'hidden' },
  moduleChip: { width: 28, height: 28, borderRadius: 10, backgroundColor: 'rgba(34,211,238,0.12)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(34,211,238,0.3)' },
  auditRow: { borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.08)', paddingVertical: 10 },
  auditChip: { paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.06)' }
});
